# Generated by Django 3.0.5 on 2020-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('eligiblity_criteria', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
            ],
        ),
    ]
